import type { Metadata } from "next";
import { Geist, Geist_Mono, Oswald } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const theGlobe = localFont({
  src: "./fonts/TheGlobePersonalUseBold-2ORlw.ttf",
  variable: "--font-the-globe",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${theGlobe.variable} ${geistMono.variable} ${oswald.variable} antialiased`}
        // style={{ overflow: "hidden" }} // Desabilita o scroll inicialmente
      >
        {/* <LoadingApp /> */}
        {children}
      </body>
    </html>
  );
}
